2014-09-16 08:02:03,199 - [INFO] - from play in pool-75-thread-5 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2014-09-16 08:02:14,578 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8] bound to JNDI as DefaultDS

2014-09-16 08:02:14,901 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8

2014-09-16 08:02:15,359 - [ERROR] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Error in deployment
javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [Friends] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) [na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) [na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) [na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [na:na]
	at play.api.Play$.start(Play.scala:87) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) [na:na]
	at scala.util.Success.flatMap(Try.scala:200) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]

2014-09-16 08:02:15,418 - [ERROR] - from application in New I/O worker #1 


! @6jh15nnd6 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [Friends] in [models.User.Friends]]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
Caused by: javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [Friends] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) ~[na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) ~[na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[na:na]
	at play.api.Play$.start(Play.scala:87) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[na:na]
	... 15 common frames omitted

2014-09-16 08:03:10,332 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8] bound to JNDI as DefaultDS

2014-09-16 08:03:10,422 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8

2014-09-16 08:03:10,582 - [ERROR] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Error in deployment
javax.persistence.PersistenceException: Error on models.User.Friends.user  Can not find mappedBy property [models.User.User.user] 
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToOne(BeanDescriptorManager.java:874) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:697) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) [na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) [na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) [na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [na:na]
	at play.api.Play$.start(Play.scala:87) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) [na:na]
	at scala.util.Success.flatMap(Try.scala:200) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]

2014-09-16 08:03:10,586 - [ERROR] - from application in New I/O worker #1 


! @6jh161144 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[PersistenceException: Error on models.User.Friends.user  Can not find mappedBy property [models.User.User.user] ]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
Caused by: javax.persistence.PersistenceException: Error on models.User.Friends.user  Can not find mappedBy property [models.User.User.user] 
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToOne(BeanDescriptorManager.java:874) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:697) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) ~[na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) ~[na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[na:na]
	at play.api.Play$.start(Play.scala:87) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[na:na]
	... 15 common frames omitted

2014-09-16 08:05:30,941 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8] bound to JNDI as DefaultDS

2014-09-16 08:05:31,020 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8

2014-09-16 08:05:31,160 - [ERROR] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Error in deployment
javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [friends] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) [na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) [na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) [na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [na:na]
	at play.api.Play$.start(Play.scala:87) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) [na:na]
	at scala.util.Success.flatMap(Try.scala:200) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]

2014-09-16 08:05:31,163 - [ERROR] - from application in New I/O worker #1 


! @6jh169131 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [friends] in [models.User.Friends]]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
Caused by: javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [friends] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) ~[na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) ~[na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[na:na]
	at play.api.Play$.start(Play.scala:87) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[na:na]
	... 15 common frames omitted

2014-09-16 08:08:46,053 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8] bound to JNDI as DefaultDS

2014-09-16 08:08:46,123 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8

2014-09-16 08:08:46,251 - [ERROR] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Error in deployment
javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [friends] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) [na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) [na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) [na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [na:na]
	at play.api.Play$.start(Play.scala:87) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) [na:na]
	at scala.util.Success.flatMap(Try.scala:200) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]

2014-09-16 08:08:46,254 - [ERROR] - from application in New I/O worker #1 


! @6jh16k3ie - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [friends] in [models.User.Friends]]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
Caused by: javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [friends] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) ~[na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) ~[na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[na:na]
	at play.api.Play$.start(Play.scala:87) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[na:na]
	... 15 common frames omitted

2014-09-16 08:10:23,250 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8] bound to JNDI as DefaultDS

2014-09-16 08:10:23,325 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8

2014-09-16 08:10:23,461 - [ERROR] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Error in deployment
javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) [na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) [na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) [na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [na:na]
	at play.api.Play$.start(Play.scala:87) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) [na:na]
	at scala.util.Success.flatMap(Try.scala:200) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]

2014-09-16 08:10:23,463 - [ERROR] - from application in New I/O worker #1 


! @6jh16phd9 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
Caused by: javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) ~[na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) ~[na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[na:na]
	at play.api.Play$.start(Play.scala:87) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[na:na]
	... 15 common frames omitted

2014-09-16 08:11:30,541 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8] bound to JNDI as DefaultDS

2014-09-16 08:11:30,596 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8

2014-09-16 08:11:30,719 - [ERROR] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Error in deployment
javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) [na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) [na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) [na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [na:na]
	at play.api.Play$.start(Play.scala:87) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) [na:na]
	at scala.util.Success.flatMap(Try.scala:200) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]

2014-09-16 08:11:30,721 - [ERROR] - from application in New I/O worker #1 


! @6jh173d05 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
Caused by: javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) ~[na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) ~[na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[na:na]
	at play.api.Play$.start(Play.scala:87) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[na:na]
	... 15 common frames omitted

2014-09-16 08:11:49,678 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8] bound to JNDI as DefaultDS

2014-09-16 08:11:49,736 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8

2014-09-16 08:11:49,858 - [ERROR] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Error in deployment
javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) [na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) [na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) [na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [na:na]
	at play.api.Play$.start(Play.scala:87) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) [na:na]
	at scala.util.Success.flatMap(Try.scala:200) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]

2014-09-16 08:11:49,860 - [ERROR] - from application in New I/O worker #1 


! @6jh174f88 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
Caused by: javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) ~[na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) ~[na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[na:na]
	at play.api.Play$.start(Play.scala:87) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[na:na]
	... 15 common frames omitted

2014-09-16 08:12:19,671 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8] bound to JNDI as DefaultDS

2014-09-16 08:12:19,710 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8

2014-09-16 08:12:19,829 - [ERROR] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Error in deployment
javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) [na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) [na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) [na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [na:na]
	at play.api.Play$.start(Play.scala:87) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) [na:na]
	at scala.util.Success.flatMap(Try.scala:200) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]

2014-09-16 08:12:19,830 - [ERROR] - from application in New I/O worker #1 


! @6jh1767h0 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
Caused by: javax.persistence.PersistenceException: Error on models.User.User.firends  Can not find mappedBy property [user] in [models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:930) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:707) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:606) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) ~[na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) ~[na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[na:na]
	at play.api.Play$.start(Play.scala:87) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[na:na]
	... 15 common frames omitted

2014-09-16 08:12:43,146 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8] bound to JNDI as DefaultDS

2014-09-16 08:12:43,179 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8

2014-09-16 08:12:43,312 - [ERROR] - from com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager in play-internal-execution-context-1 
Error in deployment
java.lang.RuntimeException: Can not find Master [class models.User.User] in Child[models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocMany.initChildMasterProperty(BeanPropertyAssocMany.java:660) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocMany.initialise(BeanPropertyAssocMany.java:121) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.initialiseOther(BeanDescriptor.java:619) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.initialiseAll(BeanDescriptorManager.java:363) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:253) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) [na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) [na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) [na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) [na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) [na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) [na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [na:na]
	at play.api.Play$.start(Play.scala:87) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) [na:na]
	at scala.util.Success.flatMap(Try.scala:200) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) [na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]

2014-09-16 08:12:43,314 - [ERROR] - from application in New I/O worker #1 


! @6jh177ga6 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[RuntimeException: Can not find Master [class models.User.User] in Child[models.User.Friends]]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
Caused by: java.lang.RuntimeException: Can not find Master [class models.User.User] in Child[models.User.Friends]
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocMany.initChildMasterProperty(BeanPropertyAssocMany.java:660) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocMany.initialise(BeanPropertyAssocMany.java:121) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.initialiseOther(BeanDescriptor.java:619) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.initialiseAll(BeanDescriptorManager.java:363) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:253) ~[na:na]
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:114) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:204) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:65) ~[na:na]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58) ~[na:na]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[na:na]
	at play.api.Play$.start(Play.scala:87) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[na:na]
	... 15 common frames omitted

2014-09-16 08:14:04,558 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8] bound to JNDI as DefaultDS

2014-09-16 08:14:04,592 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb?characterEncoding=UTF-8

2014-09-16 08:14:04,981 - [ERROR] - from application in New I/O worker #1 


! @6jh17c758 - Internal server error, for (GET) [/] ->

play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486) ~[na:na]
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:507) ~[na:na]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:461) ~[na:na]
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:459) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:459) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:88) ~[na:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:88) ~[na:na]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[na:na]
	at play.api.Play$.start(Play.scala:87) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:139) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:112) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at scala.util.Success.flatMap(Try.scala:200) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:110) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]

